apiVersion: v1
kind: Service
metadata:
  namespace: ordering
  labels:
    app: simple-shop
    component: ordering
  name: ordering
spec:
  ports:
  - name: http
    protocol: TCP
    port: 7003
    targetPort: 7003
  selector:
    app: simple-shop
    component: ordering