apiVersion: v1
kind: Service
metadata:
  namespace: ordering
  labels:
    app: simple-shop
    component: ordering
  name: ordering
spec:
  ports:
  - port: 7003
  selector:
    app: simple-shop
    component: ordering